name: Node.js Package
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
        # Defaults to the user or organization that owns the workflow file
        scope: '@tap_team'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - run: pnpm add @vkontakte/vk-bridge --save-peer
    - run: pnpm run lint-check && yarn run test
    - run: pnpm version ${{ github.event.Inputs.version }} --allow-same-version
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
